### ISSUE TITLE
Do you guys have a slack channel for quesions etc

### ISSUE THREAD

**Issue by deepanshutyagi** [HyperLink-Technology/brownie#137]
* `brownie` Version: x.x.x
* `py-solc-x` Verision: x.x.x
* `solc` Version: x.x.x
* Python Version: x.x.x
* OS: osx/linux/win

### What was wrong?

Please include information like:

* full output of the error you received
* what command you ran
* the code that caused the failure

**Comment by iamdefinitelyahuman** [comment]
Sorry, not at present.  This will likely change once Brownie moves out of beta.

You can find me on Telegram with the same handle I use here on Github if you'd like.
