### ISSUE TITLE
File "brownie/project/sources.py", line 135, in get_fn IndexError: list index out of range

### ISSUE THREAD

**Issue by avatar-lavventura** [HyperLink-Technology/brownie#141]
* `brownie` Version: brownie 1.0.0b7
* `solc` Version: 0.5.7
* Python Version: 3.5
* OS: osx

Contact that works on `Brownie v1.0.0b2` does not work on `Brownie v1.0.0b7`. The error I am having when I try to compile using `brownie compile`.

```
$ brownie compile
Using solc version v0.5.7
Brownie v1.0.0b7 - Python development framework for Ethereum

Using solc version v0.5.7
Compiling contracts...
Optimizer: Enabled  Runs: 200
 - eBlocBroker.sol...
 - Lib.sol...
 - eBlocBrokerInterface.sol...
  File "brownie/cli/__main__.py", line 66, in main
    importlib.import_module("brownie.cli."+args['<command>']).main()
  File "brownie/cli/compile.py", line 24, in main
    project.load(project_path)
  File "brownie/project/__init__.py", line 91, in load
    Build()._load()
  File "brownie/project/build.py", line 67, in _load
    build_json = compiler.compile_contracts(changed_paths)
  File "brownie/project/compiler.py", line 59, in compile_contracts
    return _compile_and_format(input_json)
  File "brownie/project/compiler.py", line 80, in _compile_and_format
    compiled = _generate_pcMap(compiled)
  File "brownie/project/compiler.py", line 183, in _generate_pcMap
    'fn': sources.get_fn(contract, last[0], last[0]+last[1])
  File "brownie/project/sources.py", line 135, in get_fn
    if start < offsets[-1][1]:
IndexError: list index out of range
```

=> How could I fix this error?

**Comment by iamdefinitelyahuman** [comment]
Sorry about that. Try deleting the ``build`` folder within your project.  This will force a complete recompile of the project which (I think) should fix the issue.

**Comment by avatar-lavventura** [comment]
After deleting the `build` folder still I am facing with the same error.

**Comment by iamdefinitelyahuman** [comment]
I was able to replicate the issue by compiling a contract without any functions.  Do you have a contract like this in your project?

This issue has been fixed in the upcoming release.  I'm still a couple of days away from pushing to pypi but you can clone the [1.0.0b8](https://github.com/HyperLink-Technology/brownie/tree/v1.0.0b8) branch and install it using setuptools.

**Comment by avatar-lavventura** [comment]
I have a `.sol` file that contains an interface. 

```
pragma solidity ^0.5.7;

interface eBlocBrokerInterface {
      event hello(uint val);
      ...
}
```
