### ISSUE TITLE
Use pytest for testing

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [HyperLink-Technology/brownie#46]
Fairly self explanatory.  pytest is well known and battle tested, so probably a better approach than my own self-rolled alternative :)

**Comment by ashishmerani** [comment]
@iamdefinitelyahuman Agreed! Any ideas on How to get started? Is there a slack channel for discussion on this?

**Comment by iamdefinitelyahuman** [comment]
We've set up a [gitter](https://gitter.im/HyperLink-Technology/community), would be happy to make a plan for how to do this.
