### ISSUE TITLE
failed to GET http://worldclockapi.com/api/json/est/now with status 403 Forbidden:

### ISSUE THREAD

**Issue by ashishmerani** [HyperLink-Technology/brownie#51]
### Error message - 
Error 403 - This web app is stopped.
The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

If you are the web app administrator, please find the common 403 error scenarios and resolution here. For further troubleshooting tools and recommendations, please visit Azure

### Steps to reproduce:
1. `git clone https://github.com/HyperLink-Technology/brownie.git`
2. `cd /brownie`
3. `docker build .`

**Comment by subos2008** [comment]
It’ll be the cache busting line - it relies on an external freely provided
service to be up.

Check the Dockerfile matches the one in the dev branch perhaps.

If there are still issues with the remote service just comment out that
line or we could replace it with a more reliable one.

**Comment by subos2008** [comment]
Docker should tell you which command it was executing when the build
failed. Would be useful info in bug reports to be sure.

**Comment by ashishmerani** [comment]
Yes.
It's that line - `ADD http://worldclockapi.com/api/json/est/now /tmp/bustcache`
(https://github.com/HyperLink-Technology/brownie/blob/c0f233e6dc5ffd08e1972735ad69ff7fba27ff48/Dockerfile#L33)

**Comment by ashishmerani** [comment]
If you navigate to that link. It essentially is the same error.

**Comment by subos2008** [comment]
Yeah so that line essentially forces docker to “always run” any lines after it when you build. Normally it would just cache any line that hadn’t changed.

It allows us to pull in a new version of brownie if one is available.

But if the service we’ve chosen to point to is unreliable it will cause the build to fail.

We can:

1. remove the line but it will mean we don’t get new versions of brownie when we build
2. remove the line and run with —no-cache to get new versions of brownie - but that will re-do the entire dockerfile
3. choose a more reliable external service - it could probably just throw google.com <http://google.com/> in to a file and that would work

**Comment by ashishmerani** [comment]
- How are we getting new version of brownie from that URL (http://worldclockapi.com/api/json/est/now)?
- What is the purpose behind making that call ? It's a world clock api ? why call it ?

**Comment by subos2008** [comment]
Please see the comments on the proceeding lines in the Dockerfile..

**Comment by ashishmerani** [comment]
ok the setup now makes sense.
Besides the options that you mentioned above. There is one more-
in Dockerfile add
```
ARG XYZ=1 
RUN echo $XYZ
```
then build it with
```
docker build -t your-image --build-arg XYZ=test .
```
but drawback is end user has to specify a different value for XYZ on each build.

IMO - we should look at replacing that URL with something more reliable. (as you mentioned above)
I'll make a PR

**Comment by ashishmerani** [comment]
Tried to make a PR 
``` Permission to HyperLink-Technology/brownie.git denied ``` ?

**Comment by subos2008** [comment]
You can use $(date) to provide a unique value each build. You’ll need to have a google to find the exact arguments to pass to date. One that just prints the unix timestamp would be perfect I guess.

**Comment by ashishmerani** [comment]
``` $(date +%s) ``` should do it

**Comment by ashishmerani** [comment]
What's the process for a pull request, I get access denied while trying to push a branch?

**Comment by Asmeble** [comment]
Try changing directories maybe?
or a sub-container?

**Comment by iamdefinitelyahuman** [comment]
Closing - 1.0.0b installs via pip and the dockerfile is no longer provided.
