### ISSUE TITLE
Simplify retrieving data from events

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [HyperLink-Technology/brownie#52]
Instead of:

`id_ = tx.events[2]['data'][0]['value']`

it would be much simpler to type:

`id_ = tx.events['NewAuthority']['id']`

Need to give this some thought. Multiple firings of the same event in the same tx will complicate it, but there must be a way..

**Comment by avatar-lavventura** [comment]
Following code might help to create a dictionary through its listing format.

```
event_dict = dict()
for i in range(0, len(tx.events[0]['data'])):
      event = tx.events[0]['data'][i]
      event_dict[event['name']] = str(event['value'])

print(event_dict[<name>])
```

**Comment by iamdefinitelyahuman** [comment]
OK, I've just merged an update that implements a better way to deal with this.  It will be properly documented when I push the new API docs in the next day or two.

**Comment by avatar-lavventura** [comment]
Thanks @iamdefinitelyahuman
