### ISSUE TITLE
Add native command to compile the contracts

### ISSUE THREAD

**Issue by montyly** [HyperLink-Technology/brownie#69]
Hi,

Would it be possible to have a native `brownie compile` or `brownie build` command?

It's common to want to compile the contracts without running the tests or a specific script. It will also facilitate the integration with third-party tools; we are looking at adding native brownie support to all the [crytic](https://github.com/crytic/) tools (including [Slither](https://github.com/trailofbits/slither/), [Echidna](https://github.com/crytic/echidna) and [Manticore](https://github.com/trailofbits/manticore)).

Thanks!

**Comment by iamdefinitelyahuman** [comment]
Easy :)  Will push a new version shortly.

Also, relating to #45, I intend to add a `brownie analyze` command that initiates your tooling on a project.  Possibly allow for integration such as automatic runs whenever a contract is recompiled, or at regular intervals.  I haven't fully thought this through yet, but it's awesome to hear that you're thinking about similar things.
