### ISSUE TITLE
Version on pip lacks the web3 dependency

### ISSUE THREAD

**Issue by montyly** [HyperLink-Technology/brownie#70]
Hi,

You might be already aware, but if brownie is installed through pip, `web3` will not be installed, leading to this error:
```
ModuleNotFoundError: No module named 'web3'
```

An installation through git does not have the issue.

**Comment by iamdefinitelyahuman** [comment]
Yeah, the issue is from a missing blank line at the end of requirements.txt - will fix it on pypi here right away.  Thanks :)
