### ISSUE TITLE
Through using script how could I return the used_gas of a transaction call?

### ISSUE THREAD

**Issue by avatar-lavventura** [HyperLink-Technology/brownie#84]
I was wondering is it possible to return and print the transaction's used `gas` through script.

When I print returned value of the transaction call it returns me the transaction object I guess along with its transaction_receipt. But in addition to that how could I obtain its consumed gas and maybe additional information related to that transaction?

```
tx = my_contract().function({'from': accounts[0]})
print(tx)
```

The output I get:

```
<Transaction object '0xc1feb1714b6f7ffb5b0b232484c6a1c5d937bf55a9d36b3c0b42052566d956bc'>
```

When I do `tx.` and tab in console it doesn't return me its functions that I can use.

**Comment by avatar-lavventura** [comment]
Following approach solved my problem:

`print(' => GasUsed:' + str(tx.__dict__['gas_used']))`

**Comment by iamdefinitelyahuman** [comment]
The documentation for ``TransferReceipt`` will probably help.

https://eth-brownie.readthedocs.io/en/latest/api.html#transactions

You can print ``tx.gas_used`` or if you want more detailed information, use ``tx.info()``
