### ISSUE TITLE
Is it possible to pass some number of block number during test script in between Txs?

### ISSUE THREAD

**Issue by avatar-lavventura** [HyperLink-Technology/brownie#85]
During testing my script, in between transaction calls I want to pass `N` number of blocks on the ganache blockchain,  if possible.

Populus had something as follows: `chain.wait.for_block(100)`, but there is no `chain` object exist on brownie; is there any alternative object for the `chain` object?

```
print(web3.eth.blockNumber) # prints: 100
tx = token.setValue({'from': accounts[0]}) 
tx = token.setValue({'from': accounts[0]}) 
print(web3.eth.blockNumber) # prints: 100

tx = token.setValue({'from': accounts[0]}) 
print(web3.eth.blockNumber) # prints: 100
chain.wait.for_block(100) # I want to pass 100 blocks on the blockchain ...
print(web3.eth.blockNumber) # prints: 200
tx = token.setValue({'from': accounts[0]})
```

**[Q]** Does` Brownie` provide this, if yes how?

**Comment by iamdefinitelyahuman** [comment]
Yes, it's possible using the ``rpc`` class: https://eth-brownie.readthedocs.io/en/latest/api.html#rpc

```python
>>> web3.eth.blockNumber
1
>>> rpc.mine(100)
Block height at 100
```

It's available in the immediately when you load the console.  From a script, either ``from brownie import *`` or ``from brownie.network import rpc``

Sorry the documentation on this is a bit lacking, I'm in the process of updating it!

**Comment by avatar-lavventura** [comment]
Thanks @iamdefinitelyahuman , works like charm.

**Comment by avatar-lavventura** [comment]
@iamdefinitelyahuman : Once a while I keep get following error: `SystemError: RPC is not active.` while `ganache-cli` works on the background. 

How could I pretend the error from happening? Is it related to `ganache-cli` or `brownie`?

**Comment by iamdefinitelyahuman** [comment]
Brownie loads ``ganache-cli`` itself when it loads. If you already have ganache running, it won't recognize that.

I need to document this behaviour and maybe make brownie check for a running copy of ganahe...

**Comment by avatar-lavventura** [comment]
Thanks @iamdefinitelyahuman ; when I close the `ganache-cli` working on the background, it solved the issue. But I realize `brownie` works faster if `ganache-cli` works on the background.
