### ISSUE TITLE
How to obtain event via an mapping key?

### ISSUE THREAD

**Issue by avatar-lavventura** [HyperLink-Technology/brownie#86]
Related to [TransactionReceipt.events](https://eth-brownie.readthedocs.io/en/latest/api.html?highlight=event#TransactionReceipt.events), which returns `list` instead of a dictionary.

I was not able to obtain the event with its mapping key, is it possible in different approach?

The way I am able to obtain the event value only by the `index` of the list =>
`tx.events[0]['data'][<index>]['value']`

-----

```
for i in range(0, len(tx.events[0]['data'])):
      print(tx.events[0]['data'][i])
```

output:

```
{'name': 'clusterAddress', 'type': 'address', 'value': '0xe0cb57839ad45c3497fafb9b148ff9b11a21f33c', 'decoded': True}
{'name': 'jobKey', 'type': 'string', 'value': 'QmWmyoMoctfbAaiEs2G46gpeUmhqFRDW6KWo64y5r581Vd', 'decoded': True}
{'name': 'index', 'type': 'uint256', 'value': 0, 'decoded': True}
```

**Comment by iamdefinitelyahuman** [comment]
Related to #52 - I thought about this but I haven't dealt with it yet.  I will mark it as a priority.  Closing this issue for now as a duplicate.
